# Generated by Django 6.0 on 2025-12-27 23:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('video_id', models.CharField(blank=True, max_length=32)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('mode', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('format_id', models.CharField(blank=True, max_length=32)),
                ('ext', models.CharField(blank=True, max_length=10)),
                ('quality_label', models.CharField(blank=True, max_length=80)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('browser', models.CharField(blank=True, max_length=80)),
                ('os', models.CharField(blank=True, max_length=80)),
                ('device', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='download_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
