# Generated by Django 6.0 on 2025-12-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('downloader', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='downloadevent',
            options={'ordering': ['-created_at']},
        ),
    ]
